### ISSUE TITLE
Security Advisory

### ISSUE THREAD

**Issue by markusobi0** [opentelekomcloud-docs/docsportal#101]
https://docs.otc.t-systems.com/docsportal/security/index.html

"This content will never be shown on real deployment, since we only need a redirect to /security, which will be processed by the reverse proxy and serve corresponding content."

**Comment by edthamm** [comment]
To add a bit more content here.

The page currently displayed in production is this:

![otc_docs_config_security_missing_redirect](https://user-images.githubusercontent.com/758377/233270265-207c2b2b-8b8a-4ca4-b697-818fcba0c280.png)

It would be nice to correctly redirect here.
Thanks for taking care of this.

**Comment by tischrei** [comment]
@vladimirhasko will delete this orphan code and the page will disappear, soon.

**Comment by eduardOrthopy** [comment]
@tischrei and the content that should have been displayed here all that time will be found where?

**Comment by tischrei** [comment]
@Nils-Magnus could you have a look on this issue from content side?

**Comment by tischrei** [comment]
Did you check that @Nils-Magnus

**Comment by tischrei** [comment]
Any results @Nils-Magnus ?

**Comment by SebastianGode** [comment]
Is completed
