### ISSUE TITLE
https://docs.otc.t-systems.com/en-us/productdesc-elb/elb_pro_0004.html leads to 404

### ISSUE THREAD

**Issue by cedricbieder** [opentelekomcloud-docs/docsportal#123]
https://docs.otc.t-systems.com/en-us/productdesc-elb/elb_pro_0004.html from "learn more" button at elb creation leads to 404

**Comment by tischrei** [comment]
Where exactly did you find this link?
I think it should lead to this location: https://docs.otc.t-systems.com/cloud-container-engine/umn/best_practice/index.html

**Comment by lhajba** [comment]
This is a broken link on ELB create page, we are aware of the issue, ticket was created, waiting to be fixed.

**Comment by tischrei** [comment]
The issue will be changed asap. The link points to a wrong direction.

**Comment by tischrei** [comment]
Do we have an update on this @vladimirhasko

**Comment by vladimirhasko** [comment]
fixed and closed
