### ISSUE TITLE
Typo in redirect mapping table

### ISSUE THREAD

**Issue by Nils-Magnus** [opentelekomcloud-docs/docsportal#131]
On several HC pages, there's a link in the content part, pointing the reader to the Cloud Handling Service, for example:

  http://docs.otc.t-systems.com/volume-backup-service/umn/operation_guide/quotas.html
  http://docs.otc.t-systems.com/private-link-access-service/umn/getting_started/manual_provisioning/enabling_plas_ec.html

I found more than 100 of such hits and they are all in the text content part of the page, not the navigational controls. These pages themselves are all correct. However, their link targets point to

  https://docs.otc.t-systems.com/en-us/public/learnmore.html
  (for reference see https://docs-archive.otc.t-systems.com/en-us/public/learnmore.html

This link target is apparently handled by the mapping table. **This mapping table is redirecting via 301 to a wrong target due to a typo:**

```
$ curl -Li https://docs.otc.t-systems.com/en-us/public/learnmore.html
HTTP/2 301
date: Tue, 31 Oct 2023 12:16:00 GMT
content-type: text/html
content-length: 169
location: https://docs.otc.t-systems.comhttps://open-telekom-cloud.com/en/contact
strict-transport-security: max-age=15724800; includeSubDomains

curl: (6) Could not resolve host: docs.otc.t-systems.comhttps
````

**Comment by vladimirvshivkov** [comment]
fixed and deployed via https://github.com/opentelekomcloud-infra/system-config/pull/934

**Comment by Nils-Magnus** [comment]
Cool, works for me (after clearing the redirect cache). Closed.
