### ISSUE TITLE
some search results lead to 404

### ISSUE THREAD

**Issue by vladimirhasko** [opentelekomcloud-docs/docsportal#134]
https://docs.otc.t-systems.com/cloud-container-engine/apis/cluster_management/creating_a_cluster.html

![image](https://github.com/opentelekomcloud-docs/docsportal/assets/32979462/3f37579f-a93b-48fa-971b-c813db5afcb7)

**Comment by tischrei** [comment]
Seems to be solved after our latest updates with proper config for each service. Please check again @vladimirhasko

**Comment by SebastianGode** [comment]
Not solved @tischrei 
![image](https://github.com/opentelekomcloud-docs/docsportal/assets/70581801/914de1c6-112a-4567-a38d-35ccbb11efbd)
