### ISSUE TITLE
Display Cloud Create on OTC docs homepage

### ISSUE THREAD

**Issue by trihoangvo** [opentelekomcloud-docs/docsportal#145]
We have pushed the content of Cloud Create to the main branch at https://github.com/opentelekomcloud-docs/cloud-create

But the content is still empty: https://docs.otc.t-systems.com/cloud-create/index.html

Also the homepage https://docs.otc.t-systems.com should display a link to Cloud Create docs under the tab "Management & Deployment".

**Comment by tischrei** [comment]
Cloud Create is properly integrated. Please send us a logo for it, that we can add this.
