### ISSUE TITLE
Redirect / Link in for KMS Docu

### ISSUE THREAD

**Issue by nbruell** [opentelekomcloud-docs/docsportal#146]
The link for KMS Scenario das not work: https://docs.otc.t-systems.com/en-us/usermanual/kms/en-us_topic_0034474372.html

**Comment by vladimirhasko** [comment]
this document is not available in the source documentation, we need to ask respective squad members to deliver the missing content.

**Comment by tischrei** [comment]
Moved the request to proper repository:
https://github.com/opentelekomcloud-docs/key-management-service/issues/35
 I will close this one.
