### ISSUE TITLE
CDM > Job Management > Concurrent Extractors: 404 error

### ISSUE THREAD

**Issue by fraenkDUS** [opentelekomcloud-docs/docsportal#149]
https://docs.otc.t-systems.com/en-us/sqlref-spark-dli/dli_08_0095.html#section3

![image](https://github.com/opentelekomcloud-docs/docsportal/assets/34756092/3de370b9-976e-4c12-a24f-3d9eaea6c982)

![image](https://github.com/opentelekomcloud-docs/docsportal/assets/34756092/bc3eb193-1806-4109-8f2c-73e814e64b99)

**Comment by fraenkDUS** [comment]
Working link to the Huawei documentation: https://support.huaweicloud.com/intl/en-us/sqlref-spark-dli/dli_08_0095.html#section3

**Comment by tischrei** [comment]
The issue should be fixed. Could you verify this?
