### ISSUE TITLE
Swisscloud WAF Console

### ISSUE THREAD

**Issue by nbruell** [opentelekomcloud-docs/docsportal#153]
if I click on "learn more" on the WAF Console / Website, I forward to a 404 Side:
![grafik](https://github.com/opentelekomcloud-docs/docsportal/assets/59666563/08e09d58-dbf6-422c-a8e1-b06c4aeb9ea6)

**Comment by vladimirhasko** [comment]
this is not docsportal issue, but UI misconfiguration issue, please address it back to vendor.
See the details here
https://github.com/opentelekomcloud-infra/system-config/issues/971
