### ISSUE TITLE
Menu bar - wrong link to Enterprise Dashboard

### ISSUE THREAD

**Issue by Roboe77** [opentelekomcloud-docs/docsportal#154]
Hi,

if you click on the left menu bar on the link ""Enterprise Dashboard", you will be directly routed to the login page and not to the documentation page.
The documentation page is only reachable via the link in the middle (see screenshot)

![image](https://github.com/opentelekomcloud-docs/docsportal/assets/105854403/003558a9-2c03-412c-93ff-12c7d026f874)

The link to the Dashboard is already available if you manage to enter the ED User manual pages: (https://docs.otc.t-systems.com/enterprise-dashboard/umn/index.html)
![image](https://github.com/opentelekomcloud-docs/docsportal/assets/105854403/fb55573c-735f-4285-920e-15e3e6467393)

**Comment by Roboe77** [comment]
Thanks. It is not clear for sure.
I suggest to use the left menu bar to jump into the documentation and highlight the link there on the main page.

**Comment by tischrei** [comment]
As said, we will rework a lot. The strategy will be to have direct links to (external) applications on the left and most of the documentation in the middle section. But we are currently working on another project which needs to be finished first.

**Comment by p4sI** [comment]
I will add it here as it belongs also to the Enterprise Dashboard:
If you click in header on the Management -> Enterprise Dashboard it links to the IaC documentation
![image](https://github.com/opentelekomcloud-docs/docsportal/assets/5518425/474935c5-5b6b-4ac4-9c0f-d1b9c9ce1f92)

**Comment by tischrei** [comment]
@p4sI this is fixed now
