### ISSUE TITLE
CCE Master Nodes - Link in UI to documentation returns 404

### ISSUE THREAD

**Issue by sekoban** [opentelekomcloud-docs/docsportal#174]
CCE Master Nodes - Link in UI to documentation returns 404

The following URL retruns a 404
https://docs.otc.t-systems.com/en-us/usermanual2/aom/aom_06_0009.html

![2024-05-02 10_27_39-Cloud Container Engine - Console](https://github.com/opentelekomcloud-docs/docsportal/assets/60689864/e4d2a7aa-4bee-4d27-ac4a-073e6ea2ed93)

**Comment by oeotvos** [comment]
Thank you for the notice. Internal bug id: CONT-2498

**Comment by oeotvos** [comment]
The wrong hyperlink

https://docs.otc.t-systems.com/en-us/usermanual2/aom/aom_06_0009.html

was updated to 

https://docs.otc.t-systems.com/en-us/usermanual/aom/aom_06_0009.html

Thank you for your notice.
