### ISSUE TITLE
Suggestion Page for RDS PG Parameter Tuning is not available on SOTC

### ISSUE THREAD

**Issue by Wolfslicht** [opentelekomcloud-docs/docsportal#176]
Hey there,

Was trying to get the Sheet for RDS PG Parameter Tuning.
Sadly this ends in 404 Page not found.

Current Behavior: Link is deadened in 404
Expected behavior: Link forwards to Sheet for RDS PG Parameter Tuning

Link
https://docs.sc.otc.t-systems.com/en-us/usermanual-rds/rds_pg_10_0001.html

Tanks a lot
Wolfgang Schröder

**Comment by vladimirhasko** [comment]
@Wolfslicht do you refer to Swisscloud or OTC Public Cloud.
If SwissCloud then issues should be raised in https://github.com/opentelekomcloud-docs-swiss/docsportal
but we will look at the issue
thanks for spotting it

**Comment by Wolfslicht** [comment]
I was forwarded from the 404 of the Swiss OTC --> But I will raise the issue on the given link.
Thanks
