### ISSUE TITLE
page "Set alarm action rules and message templates. Learn more" return 404

### ISSUE THREAD

**Issue by lreneral** [opentelekomcloud-docs/docsportal#182]
The page in AOM under alarm Action Rules returns 404.
Set alarm action rules and message templates.[ Learn more](https://docs.otc.t-systems.com/en-us/usermanual/aom/aom_02_0933.html)
The url: https://docs.otc.t-systems.com/en-us/usermanual/aom/aom_02_0933.html

**Comment by tischrei** [comment]
Any further info on this @vladimirhasko or @sziuzko

**Comment by sziuzko** [comment]
Dear @tischrei 
The problem should be fixed. Please check..

**Comment by tischrei** [comment]
Works again, I close the ticket. Thanks for the support @sziuzko
