### ISSUE TITLE
API Gateway (APIG) Developer Guide Page not found

### ISSUE THREAD

**Issue by EbruOe** [opentelekomcloud-docs/docsportal#183]
I tried to open this page but there is an error message 404 Page not found

Here is the link: https://docs.otc.t-systems.com/api-gateway/dev-guide/

**Comment by vladimirhasko** [comment]
hi @EbruOe , We prepared just placeholder for future documentation entry for APIGW but the document is not developed yet. we have removed this entry fro APIGW base view.
Sorry for inconvenience.
