### ISSUE TITLE
training.open-telekom-cloud.com - Documentation tab with the link to the https://docs.otc.t-systems.com/en-us/ - reports 404

### ISSUE THREAD

**Issue by Petrisko1980** [opentelekomcloud-docs/docsportal#186]
Hello admin, 
Please, fix the issue with reported 404 clicked on the link in the learning module - (https://training.open-telekom-cloud.com/content/lessons/220/E-Learning-OTC-EL-MOD2_20200313_V1_-_Storyline_output/index_lms_html5.html)
Modification tab-> link does not work https://docs.otc.t-systems.com/en-us/

Thanks
P.

**Comment by vladimirhasko** [comment]
Thanks I'm working on it

**Comment by vladimirhasko** [comment]
fixed now
