### ISSUE TITLE
Improvement - Exact matching search - For example "CentOS 6" or "CentOS 7.7" for the documentation?

### ISSUE THREAD

**Issue by jhermann-github** [opentelekomcloud-docs/docsportal#189]
To quickly find outdated references in the documents, the searching by exact matches would be very helpful:
![image](https://github.com/opentelekomcloud-docs/docsportal/assets/102295233/6f9e7043-d8e1-4c0a-bbc9-8b862f58b908)

**Comment by SebastianGode** [comment]
Will be fixed with https://github.com/opentelekomcloud/otcdocstheme/pull/248

**Comment by SebastianGode** [comment]
PR merged, feature available tomorrow.
