### ISSUE TITLE
"Glossary" page on Help Center is not accessible - returns 404.

### ISSUE THREAD

**Issue by lboka** [opentelekomcloud-docs/docsportal#194]
"Glossary" page on Help Center is not accessible - returns 404.

link:   https://docs.otc.t-systems.com/additional/glossary.html

![image](https://github.com/user-attachments/assets/8eb35e14-023f-4f7b-a40a-5c6ccb03ce88)

![image](https://github.com/user-attachments/assets/74d2faa3-a15b-4247-9a13-fa2e56e38cbe)

**Comment by SebastianGode** [comment]
Thanks for reporting this bug!
I will fix it asap

**Comment by tischrei** [comment]
Fixed for me, for you as well @lboka ?

**Comment by tischrei** [comment]
fixed
