### ISSUE TITLE
"Glossary"  page  needs to update 3 lines - GaussDB NoSQL rename to GeminiDB

### ISSUE THREAD

**Issue by lboka** [opentelekomcloud-docs/docsportal#195]
"Glossary"  page   - **glossary/doc/source/index.rst**   needs to update 3 lines.
DB squad renamed former GaussDB NoSQL to GeminiDB   (temporarily both of them available in parallel on HC ).  

glossary/doc/source/index.rst:   **GaussDB NoSQL**
glossary/doc/source/index.rst:     **GaussDB NoSQL** is a distributed, non-relational, multi-model NoSQL database service with decoupled compute and storage architecture. This high availability
![image](https://github.com/user-attachments/assets/ba4b1003-5c95-4767-b8a4-cc33d57a0316)

glossary/doc/source/index.rst:     Compute nodes in the **GaussDB NoSQL** cluster.
![image](https://github.com/user-attachments/assets/d9ca1a00-39a1-46dd-a677-628964a71d8d)

**Comment by tischrei** [comment]
Thx @lboka , for highlighting this. For the next time, if you are willing to contribute by opening a Pull Request, the content is available under: https://github.com/opentelekomcloud-docs/glossary
