### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by marcospoel** [opentelekomcloud-docs/docsportal#200]
Hi,

This page is not found (https://docs-beta.otc.t-systems.com/api-ref/elastic-cloud-server/ ). It was called from:
![image](https://github.com/user-attachments/assets/e3b7bf66-c103-4fe3-a76b-fc73a5170373)
https://docs.otc-service.com/compute.html

Thank you,

**Comment by tischrei** [comment]
Thank you for highlighting your issue. There seems to be an old instance of our Helpcenter which is not supported anymore. Please use our current HC which is available under: https://docs.otc.t-systems.com/ or use the link from:

![image](https://github.com/user-attachments/assets/c0d631d9-c067-4a20-a45a-8ea1ec35256e)

Nevertheless, I am checking where this instance is coming from and will try to contact my colleagues to switch it off.

Could you please leave a quick comment if you have all details you need that I can close this issue?

**Comment by vladimirhasko** [comment]
fixed now with redirection
