### ISSUE TITLE
Redirection links vor VPN does not work properly

### ISSUE THREAD

**Issue by tischrei** [opentelekomcloud-docs/docsportal#202]
https://docs.otc.t-systems.com/en-us/qs-vpn/vpn_03_0802.html
https://docs.otc.t-systems.com/en-us/usermanual-vpn/vpn_04_0421.html
https://docs.otc.t-systems.com/virtual-private-network/umn/overview/virtual_private_network.html -- This redirection link is pointing to old document
Latest doc is-
https://docs.otc.t-systems.com/virtual-private-network/umn/

**Comment by vladimirhasko** [comment]
https://docs.otc.t-systems.com/en-us/qs-vpn/vpn_03_0802.html
this link points to document which doesn't exist on OTC, therefore I've requested to change the UI link to proper document:
https://docs.otc.t-systems.com/en-us/usermanual/vpn/vpn_qs_00003.html

https://docs.otc.t-systems.com/en-us/usermanual-vpn/vpn_04_0421.html
this link has wrong format correct one is
https://docs.otc.t-systems.com/en-us/usermanual/vpn/vpn_04_0421.html
I've requested change on UI to fix the link

https://docs.otc.t-systems.com/virtual-private-network/umn/overview/virtual_private_network.html 
this old content has been removed
