### ISSUE TITLE
Link Error

### ISSUE THREAD

**Issue by Sascha-official** [opentelekomcloud-docs/docsportal#206]
The link "learn about all **_Permissions_** supported by IAM" in chapter "Prerequisites" on page: 
https://docs.otc.t-systems.com/vpc-endpoint/umn/permissions_management/creating_a_user_and_granting_vpc_endpoint_permissions.html#vpcep-ug-0003

to the page: https://docs.otc.t-systems.com/additional/permissions.html

Results in a 404

**Comment by vladimirhasko** [comment]
fixed
