### ISSUE TITLE
MRS link error

### ISSUE THREAD

**Issue by mikacur** [opentelekomcloud-docs/docsportal#210]
The link towards "Configuring Cross-Cluster Mutual Trust Relationships" 
(https://docs.otc.t-systems.com/en-us/usermanual/mrs/mrs_01_0354.html)  
inside of MRS service UAT page creation of MRS cluster with Cerberos leads to wrong page  https://docs.otc.t-systems.com/mapreduce-service/umn/using_an_mrs_client/updating_a_client/updating_a_client_versions_earlier_than_3.html
and should lead to 
https://docs.otc.t-systems.com/mapreduce-service/umn/mrs_manager_operation_guide_applicable_to_2.x_and_earlier_versions/mrs_multi-user_permission_management/configuring_cross-cluster_mutual_trust_relationships.html

**Comment by vladimirhasko** [comment]
thanks for this issue spotting, we will have a look on the redirection problem
