### ISSUE TITLE
Any search leads to Page not Found 404

### ISSUE THREAD

**Issue by cboelle** [opentelekomcloud-docs/docsportal#219]
Any search in a UMN returns links, which cant be opened.

Example 1: ECS UMN 
![image](https://github.com/user-attachments/assets/9e3fe49a-1b9c-444c-a7a8-21027b35da6b)

Example 2: DCS UMN
![image](https://github.com/user-attachments/assets/f0dacf12-d847-4661-858f-0a517b1c0422)

**Comment by SebastianGode** [comment]
Thanks for the hint, we will fix that asap!

**Comment by SebastianGode** [comment]
Search should be working again since yesterday evening on any document.
