### ISSUE TITLE
LTS Console Links to HelpCenter not working

### ISSUE THREAD

**Issue by amuetzelgit** [opentelekomcloud-docs/docsportal#220]
For some LTS Console Links to HelpCenter the redirection/mapping is not working. The pages are available in HelpCenter.

Dashboard / landing page: all FAQ links not working
Installing Agent: https://docs.otc.t-systems.com/en-us/usermanual/lts/lts_faq_0010.html -> /umn/source/faqs/host_management/index.rst
Log Transfer:  https://docs.otc.t-systems.com/en-us/usermanual/lts/lts_faq_0040.html -> /umn/source/faqs/log_transfer/index.rst
Log Collection:  https://docs.otc.t-systems.com/en-us/usermanual/lts/lts_faq_0020.html -> /umn/source/faqs/log_ingestion/index.rst
Log Search: https://docs.otc.t-systems.com/en-us/usermanual/lts/lts_faq_0030.html -> /umn/source/faqs/log_search_and_analysis/index.rst

![image](https://github.com/user-attachments/assets/9894581f-e2b7-4e5f-83f2-a290e27e09a7)

Alarms - quick links not working
https://docs.otc.t-systems.com/en-us/usermanual/lts/lts_04_0057.html -> /umn/source/log_alarms/index.rst
![image](https://github.com/user-attachments/assets/2824ce43-7120-47b5-b9c9-767ed7a3592e)

Coniguration Center - Delimiter - link not working
https://docs.otc.t-systems.com/en-us/usermanual/lts/lts_04_0052.html ->  -> /umn/source/configuration_center/configuring_log_content_delimiters.rst
![image](https://github.com/user-attachments/assets/a247dcde-b2aa-46a9-a7de-ec85c6ccea02)

Alarm center - Create Alarm - link not working
https://docs.otc.t-systems.com/en-us/usermanual/lts/lts_04_0062.html -> /umn/source/log_alarms/alarm_rules/configuring_log_alarm_rules.rst
https://docs.otc.t-systems.com/en-us/usermanual/lts/lts_02_0926.html -> /umn/source/log_alarms/configuring_log_alarm_notifications/creating_an_alarm_action_rule.rst
![image](https://github.com/user-attachments/assets/da922bcc-de24-4328-89be-f0f7f53708dc)

**Comment by vladimirhasko** [comment]
created PR https://github.com/opentelekomcloud-infra/system-config/pull/1153

**Comment by vladimirhasko** [comment]
fixed
