### ISSUE TITLE
Please provide SMG documentation

### ISSUE THREAD

**Issue by robert1x2** [opentelekomcloud-docs/docsportal#41]
this is from old docu system:

Secure Mail Gateway User Guide
Please find attached the description for the Secure Mail Gateway solution.

[PDF](https://docs.otc.t-systems.com/smg/doc/download/pdf/smg-usermanual.pdf)
Secure Mail Gateway - Benutzerhandbuch
Im Anhang finden Sie die Beschreibung für die Secure Mail Gateway Lösung.

[PDF](https://docs.otc.t-systems.com/smg/doc/download/pdf/smg-ugs3fs.pdf)

**Comment by vladimirhasko** [comment]
SMG has been provided under network area
