### ISSUE TITLE
Footer with legal info is missing

### ISSUE THREAD

**Issue by Nils-Magnus** [opentelekomcloud-docs/docsportal#42]
Imprint, Contact, Disclaimer of Liability, TaC, and privacy statement are missing.
Copyright should be added and updated (2023).
Use https://community.open-telekom-cloud.com/ as a template for the footer. Those are all external links.

**Comment by Nils-Magnus** [comment]
Imprint should be a real copy of https://www.t-systems.com/de/en/imprint
Replace BR with Gregory Hyttenrauch, SVP

**Comment by gtema** [comment]
No real copying of the data
