### ISSUE TITLE
Include terraform into the index of docsportal

### ISSUE THREAD

**Issue by gtema** [opentelekomcloud-docs/docsportal#54]
Here are 2 points to be considered independent from each other:
- evaluate whether we can/it makes sense at all to publish build TF documentation directly to HC. Currently we only have link to TF registry (but maybe this is even ok)
- include TF into the search of HC so that we also promote TF in search results

**Comment by tischrei** [comment]
Is there any update?

**Comment by tischrei** [comment]
@Nils-Magnus could you verify this request and its validity, please.

**Comment by tischrei** [comment]
done
