### ISSUE TITLE
Vulnerability Database in HelpCenter 3.0

### ISSUE THREAD

**Issue by mafazeka** [opentelekomcloud-docs/docsportal#57]
There was a link (https://nvd.nist.gov/) to Vulnerability Database before which disappeared from HelpCenter 3.0, but it was actually a BSI C5 criteria to such database. 
Additionally, a demand might come up to have an OTC-specific Vulnerability Database. (see in OAS19-5210).

Please add again the vulnerability page and evaluate the possibility to filter it down to only OTC-relevant vulnerabilities.

**Comment by gtema** [comment]
link would be re-established.

https://github.com/opentelekomcloud-docs/security is a repository, through which we are able to communicate additional Security information towards customers. We now need to find responsible people for maintaining this information.

**Comment by mafazeka** [comment]
Responsibility should be on Service Delivery (to maintain the page and decide how to show it to customers) and Security Enablement to keep up-to-date the database. That's my humble opinion. But need to discuss with them!

**Comment by gtema** [comment]
Done

**Comment by gtema** [comment]
https://docs.otc.t-systems.com > Additional Resources > Security advisory
