### ISSUE TITLE
Link broken - Creating a NAT Gateway

### ISSUE THREAD

**Issue by robert1x2** [opentelekomcloud-docs/docsportal#58]
Hi link is broken:

https://console.otc.t-systems.com/vpc/?agencyId=f8dffd77d233414b9009c22a51fe9b30&region=eu-de&locale=en-us#/dashboard

to the right you see many links in "Quick Start Guide" at bottom "Creating a NAT Gateway" link leads to https://docs.otc.t-systems.com/en-us/usermanual/nat/en-us_topic_0150270259.html which is failing! Please repair.

**Comment by gtema** [comment]
fixed
