### ISSUE TITLE
Link Broken

### ISSUE THREAD

**Issue by robert1x2** [opentelekomcloud-docs/docsportal#59]
In Dashboard Cloud Server Console - Start Quick Guide Links to the right in OTC Console:

https://console.otc.t-systems.com/ecm/?agencyId=f8dffd77d233414b9009c22a51fe9b30&region=eu-de&locale=en-us#/dashboard

[Configuring a Key Pair](https://docs.otc.t-systems.com/usermanual/ecs/en-us_topic_0014250631.html) is broken.

**Comment by gtema** [comment]
the link on it's own is broken and points to a non-existing page (if you replace docs with docs-archive you will end up back on index)

**Comment by gtema** [comment]
@robert1x2 are you ok with a redirect to https://docs.otc.t-systems.com/elastic-cloud-server/umn/passwords_and_key_pairs/key_pairs/index.html?

**Comment by robert1x2** [comment]
yes is good :-) thx asking

**Comment by gtema** [comment]
Done
