### ISSUE TITLE
Link Broken - DWS (?)

### ISSUE THREAD

**Issue by robert1x2** [opentelekomcloud-docs/docsportal#61]
https://console.otc.t-systems.com/dws/?agencyId=f8dffd77d233414b9009c22a51fe9b30&region=eu-de&locale=en-us#/dws/management/list

see in (?) ... learn more link leads to https://docs.otc.t-systems.com/en-us/usermanual/rds/en-us_topic_dashboard.html

**Comment by vladimirhasko** [comment]
link on (?) has double slashes: https://docs.otc.t-systems.com//en-us/usermanual/dws/dws_01_0002.html
which is the bug on UI console. It needs to be fixed there

**Comment by mikacur** [comment]
Bug ticket is created
https://jira.tsi-dev.otc-service.com/browse/OTCBIGDAI-3807

**Comment by tischrei** [comment]
So issue has to be tracked in Jira. I'll close it here.
