### ISSUE TITLE
Major help link in OTC console leads to "The page you are requesting is not available"

### ISSUE THREAD

**Issue by opnmind** [opentelekomcloud-docs/docsportal#62]
If you are visiting the OTC ui console and try to click on the questionsmark in the right upper corner.

https://docs.otc.t-systems.com/?locale=en-us

Then you will receive the above mentioned result.

**Comment by markusobi0** [comment]
The old Startpage. Often set as a bookmark is also "not available"

https://docs.otc.t-systems.com/en-us/index.html

**Comment by gtema** [comment]
fixed
