### ISSUE TITLE
Link Broken - Identity Providers -> Learn more

### ISSUE THREAD

**Issue by robert1x2** [opentelekomcloud-docs/docsportal#66]
Learn more link leads into https://console.otc.t-systems.com/iam/?agencyId=f8dffd77d233414b9009c22a51fe9b30&region=eu-de&locale=en-us#/iam/identityProviders

**Comment by vladimirhasko** [comment]
this is broken on old HC as well so needs to be fixed on IAM UI console, though we can try to fix it manually (guessing the proper page)

**Comment by vladimirhasko** [comment]
@lbelejka please provide some feedback here

**Comment by tischrei** [comment]
Is this still valid? I can't see the issue here.

**Comment by lbelejka** [comment]
> Is this still valid? I can't see the issue here.

yep, issue is still persist

**Comment by zokabai** [comment]
https://docs.otc.t-systems.com/en-us/usermanual/iam/en-us_topic_0079620341.html
