### ISSUE TITLE
Link Broken - RDS -> Learn More

### ISSUE THREAD

**Issue by robert1x2** [opentelekomcloud-docs/docsportal#67]
https://console.otc.t-systems.com/newrds/?agencyId=f8dffd77d233414b9009c22a51fe9b30&region=eu-de&locale=en-us#/rds/management/list

Please recheck Learn More link in RDS headline

**Comment by gtema** [comment]
Please in future reports include precisely the link itself, and not from where it is referred

**Comment by gtema** [comment]
fixed through https://github.com/opentelekomcloud-infra/system-config/pull/748
