### ISSUE TITLE
duplicate and unclear instructions

### ISSUE THREAD

**Issue by markusobi0** [opentelekomcloud-docs/docsportal#77]
Via the Site https://docs.otc.t-systems.com/sdk.html and the Button "OTC Extensions" you come to this page which isn't correctly formatted and is a bit old: https://docs.otc-service.com/python-otcextensions/

But you can find a secondary site that seems to be a bit more updated but is externally hosted: https://python-otcextensions.readthedocs.io/en/latest/cli/index.html

**Comment by tischrei** [comment]
Thanks for your valid issue and sorry for the late response. We are going to fix that.

**Comment by tischrei** [comment]
Has been solved.
