### ISSUE TITLE
Not yet released features already linked publicly

### ISSUE THREAD

**Issue by markusobi0** [opentelekomcloud-docs/docsportal#81]
There are probably future features (which aren't released yet) on the docs main page linked, but there is no icon and the link doesn't work.

![image](https://user-images.githubusercontent.com/36815683/218888425-3eac5f08-1100-45bc-93b3-ad2e09690a87.png)

**Comment by tischrei** [comment]
My colleagues @vladimirhasko is going to hide them again.

**Comment by vladimirhasko** [comment]
it's removed now
