### ISSUE TITLE
 Missing copy Function for terminal window

### ISSUE THREAD

**Issue by vladimirhasko** [opentelekomcloud-docs/docsportal#89]
Missing copy Function for terminal window (enhancement)

![! ENH - 2022-03-23 14_15_00 Missing copy](https://user-images.githubusercontent.com/102295233/159953703-c5b51453-d766-4f1f-8803-9bcde7daac62.png)

**Comment by tischrei** [comment]
Need to check that, I thought we @SebastianGode had implemented it already

**Comment by tischrei** [comment]
![image](https://user-images.githubusercontent.com/26574398/231408590-d8ad4259-b115-4c7b-b6f2-026801714557.png)
The copy function is there while hovering the code block.

Could you check this again @vladimirhasko ? As an option we might make the grey style visible without hover effect.
