### ISSUE TITLE
Anti-DDoS Search result links dead

### ISSUE THREAD

**Issue by AdamVB** [opentelekomcloud-docs/docsportal#91]
Search for Anti-DDoS in the Search bar

All links leading to anti-ddos/ are broken

leads to 

https://docs-beta.otc.t-systems.com/anti-ddos/index.html

instead of 

https://docs.otc.t-systems.com/anti-ddos/umn/index.html

![image](https://user-images.githubusercontent.com/15871966/224277929-a2a17716-67bc-47fc-8741-e36973571ef0.png)

![image](https://user-images.githubusercontent.com/15871966/224277973-c0556abd-a305-48ba-a1b5-82ac23ca39a7.png)

**Comment by tischrei** [comment]
Thanks for your issue.
We fixed the search. Please confirm the proper functionality. If this is fine for you I will close the issue.

BR Tino

**Comment by tischrei** [comment]
If there are still isssues left, please let us know. I will close the issue. From our side it is solved.
