### ISSUE TITLE
SDK docs forward from old url not possible

### ISSUE THREAD

**Issue by markusobi0** [opentelekomcloud-docs/docsportal#96]
When accessing the old Java SDK Docs the Docs are not available
https://docs.otc.t-systems.com/devg/sdk/sdk_01_0012.html

**Comment by tischrei** [comment]
The SDK is a 3rd party one, we discuss the further procedure on it internally. Meanwhile you can use: https://docs-archive.otc.t-systems.com/devg/sdk/sdk_01_0012.html which is still working.

**Comment by tischrei** [comment]
@Nils-Magnus pls have a look on this to clarify the situation on JavaSDK and its support.

**Comment by tischrei** [comment]
I got the info that we have decided to discontinue the support and documentation of the JavaSDK. It is not maintained anymore and the documentation will not be supported as well. Nevertheless, the provided link to the archived documentation and the content stays online: https://docs-archive.otc.t-systems.com/
If you have a critical use case we might find another solution to support you. But please let us know.
