### ISSUE TITLE
Java SDK Docs missing

### ISSUE THREAD

**Issue by markusobi0** [opentelekomcloud-docs/docsportal#97]
On the Page below the Java SDK docu is missing
https://docs.otc.t-systems.com/developer/sdk.html

**Comment by tischrei** [comment]
Please clarify support on JavaSDK @Nils-Magnus

**Comment by tischrei** [comment]
@markusobi0 , I got the info that we have decided to discontinue the support and documentation of the JavaSDK. It is not maintained anymore and the documentation will not be supported as well. Nevertheless, the provided link to the archived documentation and the content stays online: https://docs-archive.otc.t-systems.com/
If you have a critical use case we might find another solution to support you. But please let us know.

**Comment by tischrei** [comment]
You might also consider to check out our community portal (https://community.open-telekom-cloud.com/community) where you might discuss your use case with our community and our "Success Managers".
